### ISSUE TITLE
Small Bug: Seller Home Screen Toggle Button 

### ISSUE THREAD

**Issue by freddychenyouren2** [cedricyeeky/orbital_NUShopLah-#20]
## Discovered on 20 July 2023 1.10am

After creating a Percentage Voucher, the screen returns to its default state, where the Card is now Dollar Voucher, which is an expected behaviour.

However, the TouchableOpacity buttons remained at Percentage Voucher. This is not optimal and can be confusing to Sellers.

![Small Bug - Percentage Voucher button remained after creation of voucher](https://github.com/cedricyeeky/orbital_NUShopLah-/assets/108988934/a4dcb7f2-7761-4601-af1a-a5518dd4584e)

**Comment by cedricyeeky** [comment]
UPDATE: SOLVED removed previous setState to dollar to prevent button shift

**Comment by cedricyeeky** [comment]
RESOLVED see previous comment
