### ISSUE TITLE
Writing Test Files for Activity Screens

### ISSUE THREAD

**Issue by freddychenyouren2** [cedricyeeky/orbital_NUShopLah-#6]
Write test files for the activity screen. Start with rendering components correctly, then test any functionality.

**Comment by freddychenyouren2** [comment]
Figured out how to mock data appropriately and use appropriate functions to test rendering and functionality

**Comment by cedricyeeky** [comment]
UPDATE: Activity test files both done for Freddy (Customer) and Cedric (Seller).

**Comment by cedricyeeky** [comment]
Both Freddy and Cedric have finished jest test files for their Activity Screens.
